{?

  write "testing";
  
  writeln ""; 
  
  writesubst " test :bool:;",{"bool":true};

  writeln "";

  writesubst " test :bool::bool:",{"bool":true};

  writeln "";

  writesubst " test :notexists: :b::out of",{"bool":false};

  writeln "";

  x := { result: "Integer",
         args: "",
         name: "SomeFunction" };
  writesubst "  procedure :NAME:(:ARGS:):::RESULT:; (*autogenerated, dont modify*)",x;

?}
