version: "3.9"

services:
  fpc-dev-container:
    build:
      context: .docker/local-dev/
      dockerfile: Dockerfile
      args:
        - WORKSPACE=/app
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
#    networks:
#      - app-net
    volumes:
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done"

#networks:
#  app-net:
#    driver: bridge
